spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/tasktracker
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: validate
hibernate:
  format_sql: 'true'
logging:
  level:
    org:
      springframework: 'INFO'
      maveric:
        currencyexchange: 'INFO'
  file:
    name: ./log/app.log